### ISSUE TITLE
Deprecated: Return type ADODB error messages

### ISSUE THREAD

**Issue by reshuler** [xlrl/docker-mantisbt#15]
After a recent update, Mantisbt is failing with large number of Deprecated: Return type ADODB error messages.

Not sure how to fix these errors.

Thanks,
Robert

**Comment by XelaRellum** [comment]
> After a recent update, Mantisbt is failing with large number of Deprecated: Return type ADODB error messages.
> 
> Not sure how to fix these errors.
> 
> Thanks, Robert

That's correct. This happened because a fix to #1 . Our image relies on php:apache which in the meantime uses php 8. Mantis doesn't seem to be compatible with that and bails out.

The fall back was to explicitely use PHP 7. Please check if this works for you so I can close the issue.

**Comment by FrancYescO** [comment]
Also PHP 8.0.x looks good.
Is broken from 8.1

**Comment by XelaRellum** [comment]
Good to know, will try this out.

Am 11. Dezember 2021 19:21:56 MEZ schrieb Francesco M ***@***.***>:
