### ISSUE TITLE
Where is the PHP.INI in MantisBT Docker version

### ISSUE THREAD

**Issue by coderunway** [xlrl/docker-mantisbt#20]
I'm using this docker version of MantisBT.
During the admin check, I found the following warning. However, to fix these, where can I find the php.ini file in the docker install of mantis to update these changes? I checked with Mantis official Forum and they asked to check with the docker team.  Can you please guide me here. Appreciate the help. 

PHP
1) register_argc_argv php.ini directive is disabled
This directive should be disabled to increase performance (it only affects PHP in CLI mode). WARN
2) display_errors php.ini directive is disabled
For security reasons this directive should be disabled on all production and Internet facing servers. WARN
3) display_startup_errors php.ini directive is disabled
For security reasons this directive should be disabled on all production and Internet facing servers. WARN

**Comment by XelaRellum** [comment]
The php.ini for local modification is in /usr/local/etc/php/php.ini

**Comment by coderunway** [comment]
Thanks this helped! Closing this now.
