### ISSUE TITLE
INTERNAL APPLICATION ERROR

### ISSUE THREAD

**Issue by coderunway** [xlrl/docker-mantisbt#21]
I'm trying to install the mantisbt docker and both mysql and mantis containers are up and running.  I can connect to mysql via the command line too.  However at the final install step  via the browser ($ firefox http://localhost:8989/admin/install.php)  after I fill in all "correct" details, It shows the below error

```
INTERNAL APPLICATION ERROR

Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section
```

I have tried the latest tag image ([2.25.7]) and also tried [2.25.6-php8.1] tag too and both give same errors. 

Appreciate some guidance.

**Comment by coderunway** [comment]
Pretty strange. After reinstalling the latest tag 4 times, it worked on the 4th attempt.

**Comment by Jardo-51** [comment]
I am experiencing the same issue right now with image 2.25.7

**Comment by XelaRellum** [comment]
I just tried the install script with an empty installation. Did you enter a valid database host in the install page? By default it is "localhost", which is not correct. E.g. in the example it is "mysql" (since that's the name of the service, but of course could be anything).

**Comment by XelaRellum** [comment]
And can you check the docker output? For me I had the following (with the wrong database host):

```
mantisbt_1  | [Fri Sep 15 12:34:16.979579 2023] [php:notice] [pid 25] [client 172.17.0.1:45516] No such file or directory\n/var/www/html/vendor/adodb/adodb-php/drivers/adodb-mysqli.inc.php: 124: - - - - mysqli_real_connect( <Object><mysqli> (  ), <string>'localhost', <string>'root', <string>'root', <string>'', <integer>3306, <string>'', <integer>0 )\n/var/www/html/vendor/adodb/adodb-php/adodb.inc.php: 695: ADODB_mysqli - -> - _connect( <string>'localhost', <string>'root', <string>'root', <string>'' )\n/var/www/html/admin/install.php: 423: ADOConnection - -> - Connect( <string>'localhost', <string>'root', <string>'root' )\n, referer: http://127.0.0.1:8989/admin/install.php
```

**Comment by Jardo-51** [comment]
Yes, turns out I also had bad DB connection configuration. I figured it out by downgrading to version 2.25.6, which displays a comprehensive error on the pre-installation check page: 

![Screenshot from 2023-09-18 12-32-21](https://github.com/xlrl/docker-mantisbt/assets/6890442/4dd8545f-6a33-42b0-897b-1171c21bad0d)

In version 2.25.7, the pre-installation check page crashes with a generic error:

![Screenshot from 2023-09-19 05-53-18](https://github.com/xlrl/docker-mantisbt/assets/6890442/a82aa4d0-d01e-4d56-bce2-e07940010745)

**Comment by XelaRellum** [comment]
So, I would say, this is an upstream issue with mantis. Maybe somebody can report it with the mantis project?
