### ISSUE TITLE
Missing option to set UID and GID

### ISSUE THREAD

**Issue by titanbird** [xlrl/docker-mantisbt#22]
Hello :-)

Sorry, I am not an expert with docker.
I really appreaciate your work with the docker image for mantisbt. Good job.

Is it true that the possibility to let the mantisbt container run with specific user ID and user group ID (UUID, UGID) is currently missing?
I can't see any line of code for it so I assume it's not implemented?
I tried to start the mantisbt container with --user 1000:100, to run it with specific user ID 1000 and specific user group ID 100.
But then the container is broken with the following log message:

> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.224.3. Set the 'ServerName' directive globally to suppress this message
> 
> (13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
> 
> no listening sockets available, shutting down
> 
> AH00015: Unable to open logs

I assume that the container is then running with another user id and group id but then the webserver can not be started because only root users are able to run webservers with port 80.

Question: Can you implement the option that I can specify specific UID and GID? I did see many other images that are offering UID and GID environment variables to define it.

Keep going, I really like it

**Comment by XelaRellum** [comment]
Can you show me images/examples of other projects that implemented this?

**Comment by XelaRellum** [comment]
No response, closing the issue for now.
