### ISSUE TITLE
Find a way to disable admin folder

### ISSUE THREAD

**Issue by yonisolo** [xlrl/docker-mantisbt#27]
Hi,
thank you for your work here!
Is there a way to disable the admin folder? 
From an another image, I had an environment var to disable it but I can't find a proper way to do it here
old code from okainov/mantisbt-docker mantis-entrypoint:
```
#!/bin/bash

set -eo pipefail

test -d admin && chmod -rx admin && mv admin .admin

# If MANTIS_ENABLE_ADMIN is set to , then enable 'admin' folder
if [ ! -z "$MANTIS_ENABLE_ADMIN" ] && [ "$MANTIS_ENABLE_ADMIN" -ne "0" ]; then
  test -d .admin && mv .admin admin && chmod +rx admin
fi

apache2-foreground
```
here setting MANTIS_ENABLE_ADMIN to 0 remove admin right in the container at startup
Don't know if it's possible, thank you again

**Comment by XelaRellum** [comment]
Thanks a lot for the suggestion. This all pointed me in the right direction. Your proposed mechanism is now enabled her and in the <https://hub.docker.com>(images)
