### ISSUE TITLE
Error during installation of db at: Schema step 65

### ISSUE THREAD

**Issue by kjones-lan** [xlrl/docker-mantisbt#5]
I've encountered an error during installation when running http://localhost:8989/admin/install.php

|description|error |
|:--|:--|
|Schema step 65: AlterColumnSQL ( mantis_user_pref_mantis )|BAD<br>ALTER TABLE mantis_user_pref_mantis MODIFY COLUMN redirect_delay INTEGER NOT NULL DEFAULT 0<br>Error on rename of './bugtracker/mantis_user_pref_mantis' to './bugtracker/#sql2-1-d' (errno: 168 "Unknown (generic) error from engine")

From the console output:
```mysql_1     | 2020-02-11 18:24:25 13 [ERROR] InnoDB: Operating system error number 16 in a file operation.
mysql_1     | 2020-02-11 18:24:25 13 [ERROR] InnoDB: Error number 16 means 'Device or resource busy'
mysql_1     | 2020-02-11 18:24:25 13 [Note] InnoDB: Some operating system error numbers are described at https://mariadb.com/kb/en/library/operating-system-error-codes/
mysql_1     | 2020-02-11 18:24:25 13 [ERROR] InnoDB: Cannot rename file './bugtracker/mantis_user_pref_mantis.ibd' to './bugtracker/#sql2-1-d.ibd'```

**Comment by XelaRellum** [comment]
Hm. Did this problem occurs to anybody else? What kind of system did you try to run this on?

**Comment by TimThaler** [comment]
Hi, i am using mariaDB and the latest mantisbt images and the installation process is working

**Comment by XelaRellum** [comment]
Ok, gonna close this now.
