### ISSUE TITLE
Logging of PHP errors,warning from the MantisBT Container

### ISSUE THREAD

**Issue by TimThaler** [xlrl/docker-mantisbt#8]
Hi,

I would like to be able to debug the email-setup, therefore want to access the PHP logs.
Currently  just the messages from the webserver are being logged  for the  MantisBT Container when checking via:

`docker logs -f --details mantisBT`

the php.ini includes now these two lines:
```
log_errors = On
error_log = /dev/stderr
```
But -apparently- still only the webserver writes to /dev/sterr/. What settings do i have to make to view the logs?

**Comment by XelaRellum** [comment]
Well searching a bit I found the following settings:
* `error_reporting` (set to something like `E_ALL`)
* `log_errors` to enable/`1` logging

**Comment by XelaRellum** [comment]
No further response so I guess this issue is resolved.
